services:

  dbpostgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=ez_client_services
    ports:
      - 5432:5432
    networks:
      - ezblue-network

  mongodb:
    image: mongo
    restart: always
    environment:
      - MONGO_INITDB_ROOT_USERNAME=mongo
      - MONGO_INITDB_ROOT_PASSWORD=mongo
      - MONGO_INITDB_DATABASE=ezblue
    ports:
      - 27017:27017
    volumes:
    - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    networks:
      - ezblue-network

  ez-eureka-server:
    restart: always
    build:
      context: ./Ez-Eureka-Server
      dockerfile: Dockerfile
    ports:
      - 8761:8761
    depends_on:
      - dbpostgres
    networks:
      - ezblue-network

  ez-gatway:
    restart: always  
    build:
      context: ./Ez-Gateway-Services
      dockerfile: Dockerfile
    ports:
      - 8080:8080
    links:
      - ez-eureka-server  
    environment:
      - EUREKA_SERVER=http://ez-eureka-server:8761/eureka/
    depends_on:
      - ez-eureka-server
    networks:
      - ezblue-network

  ez-blue-service:
    restart: always
    build:
      context: ./Ez-Blue-Services
      dockerfile: Dockerfile
    ports:
      - 8081:8081
    links:
      - dbpostgres
      - ez-gatway
    environment:
      - EUREKA_SERVER=http://ez-eureka-server:8761/eureka/
    depends_on:
      - ez-gatway
    networks:
      - ezblue-network

  ez-client-service:
    restart: always
    build:
      context: ./Ez-Client-Services
      dockerfile: Dockerfile
    ports:
      - 8082:8082
    links:
      - dbpostgres
      - ez-gatway
    environment:
      - EUREKA_SERVER=http://ez-eureka-server:8761/eureka/
      - SPRING_DATASOURCE_URL=jdbc:postgresql://dbpostgres:5432/ez_client_services
      - SPRING_DATASOURCE_USERNAME=postgres
      - SPRING_DATASOURCE_PASSWORD=postgres
      - SPRING_JPA_HIBERNATE_DDL_AUTO=update
    depends_on:
      - ez-gatway
    networks:
      - ezblue-network

networks:
  ezblue-network:
    driver: bridge
